### PR TITLE
Fix type check

### PR DESCRIPTION
**Pull request by arj03**
See https://github.com/ssbc/ssb-ref/issues/36

### CODE REVIEW

**Comment by christianbundy** [comment]
Woo! Looks great to me, thanks for fixing this.

**Comment by christianbundy** [comment]
Maybe a silly question, but why did we need to bump the index version with this PR? I understand bumping the module version, because we're changing the API (e.g. not guaranteeing that some keys will be returned) but it seems like otherwise this could be forward compatible. I'm guessing that I'm misunderstanding something though, I've only skimmed the code.

**Comment by arj03** [comment]
For me, the semantic meaning of the version number is: if I nuke the index and rerun it I will get exactly the same index as I had before. So that is why I bumped it. Also I made this a major version update and updated the README with what exactly this module indexes :)

**Comment by christianbundy** [comment]
Cool, thanks for the explanation!

**Pull request merged**
